import wallme.websites.apod
import wallme.websites.astrobin
import wallme.websites.bing
import wallme.websites.epod
import wallme.websites.guardian
import wallme.websites.nasa
import wallme.websites.nationalgeographic
import wallme.websites.telegraph
import wallme.websites.tetras
import wallme.websites.wikipedia
