name: Static analysis

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  static_analysis:
    name: Static analysis

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint with flake8
      uses: py-actions/flake8@v2
      with:
        max-line-length: "1000"
