name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
    branches: [ dev ]

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov codecov
        pip install -r requirements.txt

    - name: Test with pytest and codecoverage
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          pytest test --cov=wallme/ --cov-report=xml
        else
          sudo pytest test --cov=wallme/ --cov-report=xml
        fi
      shell: bash

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
